# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "http://oliji9s3j.bkt.clouddn.com/favicon.ico"
    high_res_favicon: "http://wx2.sinaimg.cn/mw1024/6aae3cf3gy1fcur6pcgo6j20lf0f2175.jpg"
    apple_touch_icon: "http://wx2.sinaimg.cn/mw1024/6aae3cf3gy1fcur6pcgo6j20lf0f2175.jpg"
    keywords: hive,hadoop,spark,hbase,hdfs,mapreduce,cluster 

# Jump Links Settings
url:
    rss:
    daily_pic: "/"
    logo: "/"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "孤独星球"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: false

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    markdown: Github
    entry_excerpt: 80
    code_highlight: solarized-white

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    #bgimg: "https://rrkuvvawp.s3.amazonaws.com/ltn_7ba62d4618378af6731999bf109452d920131024074325.jpeg"
    #bgimg: "http://oliji9s3j.bkt.clouddn.com/bg_new.jpg"
    bing:
        enable: false
        parameter:


# Images Settings
img:
    logo: "http://wx2.sinaimg.cn/mw1024/6aae3cf3gy1fcur6pcgo6j20lf0f2175.jpg"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily.jpeg"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    #upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/material-"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: xooglexls@gmail.com
    facebook: "https://www.facebook.com/profile.php?id=100014686742374"
    twitter: "https://twitter.com/twitter"
    googleplus: "https://www.google.com/"
    weibo: "http://weibo.com/u/1789803763/home?leftnav=1"
    instagram: 
    tumblr: 
    github: 
    linkedin: 
    zhihu: 
    bilibili: 
    telegram: 

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: false
    qq: true
    telegram: false

# Sidebar User Dropdown
dropdown:
    Email Me:
        link: "#"
        icon: email

# Sidebar Categories Switch
sidebar_categories: true

# Pages Menu
pages:
    Astan:
        link: "/aboutme/"
        #icon: person
    标签索引:
        link: "/tags/"
        #icon: person
    图库: 
        link: "/galleries/"
        #icon: person
    #邓紫棋: 
        #link: "/gallery"
        #icon: person

# Qrcode for redirect at other device
qrcode: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#     duoshuo | disqus
comment:
    use: disqus
    shortname: astan
    #duoshuo_thread_key_type: path
    #duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search: 
    use: local 
    swiftype_key:

# Leancloud Views
leancloud:
    enable: true
    app_id: f8AHUn2FOKCWoFzJTLrnSt4A-gzGzoHsz
    app_key: dOlRTKgDWf3Ut87VDHex4Wks
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
